version: '3'
services:
#  eventstore:
#    image: 'eventstore/eventstore:latest'
#    ports:
#      - '2113:2113'
#      - '1113:1113'
  activemq:
    image: ivonet/activemq
    ports:
      - '8161:8161'
      - '61616:61616'
      - '61613:61613'
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_AUTH=true
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=secret
    volumes:
      - './volumes/activemq/log:/var/log/activemq'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports: 
      - '27017-27019:27017-27019'
    expose:
      - '27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME="user"
      # - MONGO_INITDB_ROOT_PASSWORD="pass"
    volumes:
      - './volumes/mongodb/data:/data/db'
    ports:
      - '27017:27017'

  booking-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:booking-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      HOSTNAME: booking-server
      PORT: 3030
      WAIT_HOSTS: 'mongo:27017'
    entrypoint: 'npm run wait:dev:booking'
    expose:
      - '3030'
      - '56746'
    ports:
      - '3030:3030'
      - '56746:56746'
    depends_on:
      - mongo

  payment-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:payment-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      WAIT_HOSTS: 'mongo:27017'
      HOSTNAME: payment-server
      SERVICES: payments
      PORT: 3040
    entrypoint: 'npm run wait:dev:payments'
    expose:
      - '3040'
      - '56747'
    ports:
      - '3040:3040'
      - '56747:56747'
    depends_on:
      - mongo

  checkout-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:checkout-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      HOSTNAME: checkout-server
      PORT: 3050
      WAIT_HOSTS: 'mongo:27017, booking-server:3030, payment-server:3040'
    entrypoint: 'npm run wait:dev:checkout'
    expose:
      - '3050'
      - '56748'
    ports:
      - '3050:3050'
      - '56748:56748'
    depends_on:
      - payment-server
      - booking-server
