version: '3'
services:
#  eventstore:
#    image: 'eventstore/eventstore:latest'
#    ports:
#      - '2113:2113'
#      - '1113:1113'
  dynamodb: 
    image: 'amazon/dynamodb-local'
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes: 
      - './volumes/dynamodb:/home/dynamodblocal/data'
    ports: 
      - '8000:8000'

  mongo:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports: 
      - '27017-27019:27017-27019'
    expose:
      - '27017'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME="user"
      # - MONGO_INITDB_ROOT_PASSWORD="pass"
    volumes:
      - './volumes/mongodb/data:/data/db'
    ports:
      - '27017:27017'

  booking-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:booking-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      HOSTNAME: booking-server
      PORT: 3030
      WAIT_HOSTS: 'mongo:27017'
    entrypoint: 'npm run wait:dev:booking'
    expose:
      - '3030'
      - '56746'
    ports:
      - '3030:3030'
      - '56746:56746'
    depends_on:
      - mongo

  payment-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:payment-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      WAIT_HOSTS: 'mongo:27017'
      HOSTNAME: payment-server
      SERVICES: payments
      PORT: 3040
    entrypoint: 'npm run wait:dev:payments'
    expose:
      - '3040'
      - '56747'
    ports:
      - '3040:3040'
      - '56747:56747'
    depends_on:
      - mongo

  checkout-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'app:checkout-server'
    volumes:
      - '.:/usr/src/app/:rw'
    environment:
      NODE_ENV: development
      AUTH_SECRET: dTnd68c8IZjKBoKkAJQW9jciGVk=
      HOSTNAME: checkout-server
      AWS_DYNAMODB_ENDPOINT: 'http://dynamodb:8000'
      AWS_REGION: 'eu-west-1'
      PORT: 3050
      WAIT_HOSTS: 'mongo:27017, dynamodb:8000, booking-server:3030, payment-server:3040'
    entrypoint: 'npm run wait:dev:checkout'
    expose:
      - '3050'
      - '56748'
    ports:
      - '3050:3050'
      - '56748:56748'
    depends_on:
      - payment-server
      - booking-server
